### ISSUE TITLE
[Task] Create Mockup for Landing Page

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify-gallery-website#12]
**Task Description:**
Create a mockup for the landing page as part of the epic task #11 

**Deliverable(s):**
A completed mockup for the landing page, styled consistently with the rest of the website.

**Additional Context:**
Developers/designers working on the mockups should reach out to each other and have a consensus on the desired styles for the pages to ensure cohesiveness & consistency across the website.

**Comment by adel-gu** [comment]
Hi @tjtanjin @kiknalex @HusseinSerag 👋🏼 

Can you please help me take a look at the finished mockup for this? do we have it on Figma?
