### ISSUE TITLE
[Task] Add support for i18n

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify-gallery-website#36]
**Task Description:**
While english is the main medium for the website, it'll be great to extend support to other languages as well.

**Deliverable(s):**
An option should be conveniently presented for developers to change their language preferences.

**Additional Context:**
It is preferable to start on this task ASAP - the codebase grows it'll take more effort.

**Reminders:**
- Assign task to a project (required)
- Assign task to a sprint (required)
- Assign task to a developer (optional)

**Comment by anr2601** [comment]
Can I try handling this issue?

**Comment by tjtanjin** [comment]
> Can I try handling this issue?

Yes please go ahead! 😊
