### ISSUE TITLE
[Bug] loading problem of images 

### ISSUE THREAD

**Issue by nikhilchary129** [tjtanjin/react-chatbotify-gallery-website#37]
**Bug Description:**
loading problem of all images at [page](https://gallery.react-chatbotify.com/themes)

**Steps To Reproduce:**
Steps to reproduce the bug behavior:
1. Go to '[home](https://gallery.react-chatbotify.com/)'
2. Click on '[browse themes](https://gallery.react-chatbotify.com/themes)'
3. See error:

**Expected behavior:**
Display of proper images.

**Screenshots:**
![image](https://github.com/user-attachments/assets/ca291fc7-0f04-4d94-9b19-233975c5d73f)

**Desktop (please complete the following information):**
 - OS: window
 - Browser: chrome

**Mobile (please complete the following information):**
 no response.
**Additional Context:**
  no response.

**Comment by tjtanjin** [comment]
Hey @nikhilchary129, thank you very much for bringing this up. I've fixed the issue! 😊
